modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''${description}'''
#logoFile = ""
[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "${mod_id}.mixins.json"
